### ISSUE TITLE
Change of variable names in IEC models

### ISSUE THREAD

**Issue by louisg-rte** [dynawo/dyn-grid-compliance-verification#14]
for IEC WT models:
WT_wT4Injector_PGenPu --> WT_measurementsPQ_PPuSnRef (injected active power in base SnRef)
WT_wT4Injector_QGenPu --> WT_measurementsPQ_QPuSnRef (injected reactive power in base SnRef)

for IEC 2015 WT models:
WT_pQCalculus_PWtPu --> WT_measurementsPQ_PPu (injected active power in base SNom)
WT_pQCalculus_QWtPu --> WT_measurementsPQ_QPu (injected reactive power in base SNom)

for IEC 2020 WT models:
WT_controlMeasurements_PGenNomPu --> WT_measurementsPQ_PPu (injected active power in base SNom)
WT_controlMeasurements_QGenNomPu --> WT_measurementsPQ_QPu (injected reactive power in base SNom)

for IEC WPP models (new variables):
WPP_elecMeasurements_PPu (injected active power in base SNom)
WPP_elecMeasurements_QPu (injected reactive power in base SNom)
WPP_elecMeasurements_PPuSnRef (injected active power in base SnRef)
WPP_elecMeasurements_QPuSnRef (injected reactive power in base SRef)

**Comment by louisg-rte** [comment]
Some variables have changed name in the IEC models. I wanted to adapt this in Power_Park.ini and this brings me some questions:
- What is the base power (for pu) that is expected by this dictionnary ? In the modelica models some variables are in pu based on SNom (the nominal power of the unit) and others are based on SnRef (=100 MVA which is a common base power for all Modelica models). Which of them have to be written in this dictionnary ?
- For IEC WT models there is a variable called InjectedActivePower and another one called ActivePowerPu. Why do we need these 2 variables ? (same for reactive power)
![Capture d’écran de 2024-12-11 11-02-19](https://github.com/user-attachments/assets/f36cab32-cf00-47b6-8e4f-9fc6e612f7b5)

- For IEC WPP models why is there no variable corresponding to active/reactive power ?
![Capture d’écran de 2024-12-11 11-05-33](https://github.com/user-attachments/assets/354cb8bd-7552-47de-be62-9e85a9528b27)

**Comment by marcosmc** [comment]
The only conversions ​​calculated by the tool are the values needed ​​to initialize the models used (because we calculate a network power-flow); for the rest of the values, the value entered by the user is respected, so it is interpreted that it has been entered using the base that Dynawo expects for the model in each case.
We have verified that the dictionary contains variables that are no longer used, in PR #15 all variables that are no longer in use have been removed.
